plugins:
  discord_bot_enabled:
    default: true
    client: false
  discord_bot_token:
    default: 'NzQ0NjMxNDQzMzMzOTcyMTYw.XzmCEg.PaDMHcWWKVuQvNLnMa4sK1MorFM'
    client: false
  discord_bot_admin_channel_id:
    default: 744667643973468170''
    client: false
  discord_bot_admin_role_id:
    default: '744583180148801662'
    client: false
  discord_bot_rate_limit_delay:
    default: 2
    client: false
